apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
  namespace: kodeserver-control-plane
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: kodeserver-data-plane
  name: environment-creator
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "create"]
  - apiGroups: ["extensions", "apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: environment-creator-frontend
  namespace: kodeserver-data-plane
subjects:
  - kind: ServiceAccount
    name: frontend
    namespace: kodeserver-control-plane
roleRef:
  kind: Role
  name: environment-creator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: kodeserver-control-plane
spec:
  selector:
    matchLabels:
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec:
      containers:
        - name: frontend
          image: patnaikshekhar/kodespaces-frontend
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: postgresql-password
            - name: DOMAIN_NAME
              valueFrom:
                secretKeyRef:
                  name: gd-dns-provider
                  key: domain
            - name: GD_KEY
              valueFrom:
                secretKeyRef:
                  name: gd-dns-provider
                  key: key
            - name: GD_SECRET
              valueFrom:
                secretKeyRef:
                  name: gd-dns-provider
                  key: secret
            - name: PROXY_SERVICE_IP
              valueFrom:
                secretKeyRef:
                  name: gd-dns-provider
                  key: identity_service_ip
      serviceAccount: frontend
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: frontend
#   namespace: kodeserver-control-plane
# spec:
#   type: LoadBalancer
#   selector:
#     role: frontend
#   ports:
#     - port: 80
#       targetPort: 80

